FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["sh", "-c", "celery -A app.core.celery_app worker --loglevel=info --concurrency=1 & celery -A app.core.celery_app beat --loglevel=info" ]